stages:
  - build
  - deploy

docker-build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"

docker-deploy:
  stage: deploy
  tags:
    - production
  script:
    - docker image rm "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
    - docker pull "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
    - docker rm --force $(docker ps -a -f ancestor="$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" -q)
    - docker run -d --network host --restart=always --env COOKIE_MAX_AGE=$COOKIE_MAX_AGE --env PORT=$PORT --env PROTOCOL=$PROTOCOL --env URL=$URL --env REDIS_URL=$REDIS_URL --env SESSION_SECRET=$SESSION_SECRET --env SMTP_HOST=$SMTP_HOST --env SMTP_PASS=$SMTP_PASS --env SMTP_PORT=$SMTP_PORT --env SMTP_SECURE=$SMTP_SECURE --env SMTP_USER=$SMTP_USER --env URL=$URL --env MONGODB_PORT=$MONGODB_PORT --env MONGODB_HOST=$MONGODB_HOST --env MONGODB_NAME=$MONGODB_NAME --env MONGODB_USER=$MONGODB_USER --env MONGODB_PASS=$MONGODB_PASS --env MONGODB_OPTIONS=$MONGODB_OPTIONS "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
