version: "3.5"
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data:/data/db
  redis:
    image: redis
    restart: always
    volumes:
      - ./redis:/data
  web:
    build: .
    restart: always
    depends_on:
      - mongo
      - redis
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - ./emails:/usr/src/app/emails
    environment:
      - COOKIE_MAX_AGE=86400000
      - PORT=3000
      - PROTOCOL=http
      - URL="teamwork.local"
      - REDIS_URL="redis://redis:6379"
      - SESSION_SECRET="randomString"
      - SMTP_HOST="mail.local"
      - SMTP_PASS="strongPass"
      - SMTP_PORT="465"
      - SMTP_SECURE=true
      - SMTP_USER="teamworks@mail.local"
      - MONGODB_PORT=27017
      - MONGODB_HOST="mongo"
      - MONGODB_NAME="teamworks"
      - MONGODB_USER="root"
      - MONGODB_PASS="example"
      - MONGODB_OPTIONS=""
      - CONTACT_PERSON_EMAIL="somebody@example.com"
      - CORS_OPTIONS="{}"
      - OC_BASE_URL="https://cloud.example.com"
      - OC_USERNAME="admin"
      - OC_PASSWORD="admin"
      - OC_FOLDER=""
